import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#fff8f0",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#faf3e9",
        "surface-container": "#f4ede3",
        "surface-container-high": "#eee7dd",
        "surface-container-highest": "#e8e2d8",
        "surface-dim": "#e0d9cf",
        "surface-variant": "#e8e2d8",
        "surface-bright": "#fff8f0",
        "background": "#fff8f0",
        "on-surface": "#1e1b15",
        "on-surface-variant": "#40484d",
        "on-background": "#1e1b15",
        "primary": "#00526d",
        "primary-container": "#1a6b8a",
        "primary-fixed": "#c0e8ff",
        "primary-fixed-dim": "#8bcff2",
        "on-primary": "#ffffff",
        "on-primary-container": "#bce7ff",
        "on-primary-fixed": "#001e2b",
        "on-primary-fixed-variant": "#004d66",
        "inverse-primary": "#8bcff2",
        "secondary": "#ab3500",
        "secondary-container": "#fe6a34",
        "secondary-fixed": "#ffdbd0",
        "secondary-fixed-dim": "#ffb59d",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#5d1900",
        "on-secondary-fixed": "#390c00",
        "on-secondary-fixed-variant": "#832600",
        "tertiary": "#745b00",
        "tertiary-container": "#d0a600",
        "tertiary-fixed": "#ffe08b",
        "tertiary-fixed-dim": "#f0c110",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#4f3d00",
        "on-tertiary-fixed": "#241a00",
        "on-tertiary-fixed-variant": "#584400",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "outline": "#70787e",
        "outline-variant": "#bfc8ce",
        "inverse-surface": "#33302a",
        "inverse-on-surface": "#f7f0e6",
        "surface-tint": "#106885",
      },
      fontFamily: {
        "headline": ["Epilogue", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Work Sans", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};
export default config;
